name: Build React website and upload to Azure Storage Blob
on:
  workflow_dispatch:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    environment: STAGING_ENVIRONMENT
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node 18
        uses: actions/setup-node@v2
        with:
          node-version: 18.18.0
      - name: Install dependencies
        run: npm install
      - name: Build website
        run: npm run build
      - name: Store build into artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ github.sha }}
          path: dist
      - name: Azure Blob Storage Upload
        uses: bacongobbler/azure-blob-storage-upload@v3.0.0
        with:
          connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          container_name: "$web"
          source_dir: "dist"
